version: '3.9'
services:
  nginx:
    container_name: local_nginx
    image: fabiocicerchia/nginx-lua
    #image: repo.sabacell.com:5000/phoenix.trax:dev
    environment: 
      - REDIS_SERVER=172.26.0.1
    ports: 
      - 8089:80
      - 8053:8053
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/www:/usr/share/nginx/html
      - ./lib/resty/redis.lua:/usr/local/share/luajit-2.0.4/resty/redis.lua
      - ./lib/resty/kafka:/usr/local/share/lua/5.1/resty/kafka
      - ./lib/resty/JSON.lua:/usr/local/share/lua/5.1/resty/JSON.lua
    extra_hosts:
      - host.docker.internal:host-gateway    
    networks: 
      - my_network
    #network_mode: "host"

  redis: 
    container_name: local_redis
    image: redis:latest
    #command: redis-server --requirepass abcd
    ports:
      - 6379:6379
    networks:
      - my_network
    #network_mode: "host"
networks: 
  my_network:
    name: my_network  
  
