version: '3.9'
services:
  nginx:
    container_name: local_nginx
    image: fabiocicerchia/nginx-lua
    environment: 
      - REDIS_SERVER=172.26.0.1
    ports: 
      - 8089:80
      - 8053:8053
    volumes: 
      - /home/navid/lua_project/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/navid/lua_project/nginx/www:/usr/share/nginx/html
      - /home/navid/lua_project/lib/resty/redis.lua:/usr/local/share/luajit-2.0.4/resty/resis.lua
      - /home/navid/lua_project/lib/resty/kafka:/usr/local/share/lua/5.1/resty/kafka
    extra_hosts:
      - host.docker.internal:host-gateway    
    networks: 
      - my_network
    #network_mode: "host"

  redis: 
    container_name: local_redis
    image: redis:latest
    command: redis-server --requirepass abcd
    ports:
      - 6379:6379
    networks:
      - my_network
    #network_mode: "host"
networks: 
  my_network:
    name: my_network  
  