version: '3.9'
services:
  nginx:
    container_name: local_nginx
    #image: fabiocicerchia/nginx-lua
    image: repo.sabacell.com:5000/phoenix.trax:dev
    environment: 
      - REDIS_SERVER=10.11.12.162
      - REDIS_PORT=6399
      - REDIS_AUTH_KEY=u5CVSyY6o7v3JxIz
      - KAFKA_SERVER=10.11.12.162
      - KAFKA_PORT=9092
    ports: 
      - 8089:80
      - 8053:8053
    volumes: 
      - ./trax/default.conf:/etc/nginx/conf.d/default.conf
      - ./trax/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/www:/usr/share/nginx/html
      - ./lib/resty/redis.lua:/usr/local/share/luajit-2.0.4/resty/redis.lua
      - ./lib/resty/kafka:/usr/local/share/lua/5.1/resty/kafka
      - ./lib/resty/JSON.lua:/usr/local/share/lua/5.1/resty/JSON.lua
    extra_hosts:
      - host.docker.internal:host-gateway    
    networks: 
      - my_network
    #network_mode: "host"

  redis: 
    container_name: local_redis
    image: redis:latest
    #command: redis-server --requirepass abcd
    ports:
      - 6379:6379
    networks:
      - my_network
    #network_mode: "host"
networks: 
  my_network:
    name: my_network  
  